# Generated by Django 2.2.5 on 2019-12-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20191212_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulechange',
            name='degree',
            field=models.IntegerField(default=1),
        ),
    ]
