# Generated by Django 2.2.5 on 2019-12-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20191212_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulechange',
            name='degree',
        ),
    ]
