# Generated by Django 2.2.5 on 2020-02-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200111_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulechange',
            name='course',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='schedulechange',
            name='degree',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='schedulechange',
            name='absent_from',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schedulechange',
            name='absent_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schedulechange',
            name='type',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
